### ISSUE TITLE
JNumeric is having some issues.

### ISSUE THREAD

**Issue by jon4than** [Unidata/IDV#104]
It looks like `libsrc/jnumeric-2.5.1_ra0.1.jar` has some issues with Jython 2.7. Using `jnumeric-2.7.0_ra0.1.jar` from https://bitbucket.org/zornslemon/jnumeric-ra/downloads seems to fix things.

FWIW, my test is pretty simple:
```python
# run from the jython shell
import Numeric as N
a = N.array([1, 2, 3])
b = N.array([3, 2, 1])
print a, b
```
And that should output `[1 2 3] [3 2 1]`.

**Comment by jon4than** [comment]
Any thoughts or concerns?

**Comment by julienchastang** [comment]
Should be done. Let me know if you see any problems.
